// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: JsonGenerator
// Target: library
// **************************************************************************

// Generated by owl 0.1.2
// https://github.com/agilord/owl

// ignore: unused_import, library_prefixes
import 'message.dart';
// ignore: unused_import, library_prefixes
import 'dart:convert';
// ignore: unused_import, library_prefixes
import 'package:owl/util/json/core.dart' as _owl_json;

// **************************************************************************
// Generator: JsonGenerator
// Target: class Message
// **************************************************************************

/// Mapper for Message
abstract class MessageMapper {
  /// Converts an instance of Message to Map.
  static Map<String, dynamic> map(Message object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('id', object.id)
          ..put('userId', object.userId)
          ..put('text', object.text))
        .toMap();
  }

  /// Converts a Map to an instance of Message.
  static Message parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Message object = new Message();
    object.id = map['id'];
    object.userId = map['userId'];
    object.text = map['text'];
    return object;
  }

  /// Converts a JSON string to an instance of Message.
  static Message fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Message to JSON string.
  static String toJson(Message object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}
