# Default server configuration.
host: 0.0.0.0
mongo_db: mongodb://localhost:27017/chat
port: 3000
jwt_secret: "3Q133227824374JQ8217186403328618"
google:
  id: 879916772461-i7htk1jo48ubv18dbe9pvce4m6lbka9n.apps.googleusercontent.com
  secret: ZH3uaWy7Jtb7jtVRLcRRBdD0
  redirect_uri: http://localhost:3000/auth/google/callback
rethinkdb:
  host: localhost
  db: angel_chat
  user: admin
  password: ""
  port: 28015